import { Box } from '@getluko/streamline';
import { ButtonIcon } from '@getluko/streamline';

export const ButtonIconSandbox = () => (
  <Box paddingHorizontal="xl" flexDirection="row">
    <Box>
      <ButtonIcon
        accessibilityLabel="test"
        iconName="Cross"
        appearance="primary"
      />
      <ButtonIcon
        accessibilityLabel="test"
        iconName="Cross"
        appearance="secondary"
      />
      <ButtonIcon
        accessibilityLabel="test"
        iconName="Cross"
        appearance="neutral"
      />
      <ButtonIcon
        accessibilityLabel="test"
        iconName="Cross"
        appearance="danger"
      />
      <ButtonIcon accessibilityLabel="test" iconName="Cross" isLoading />
      <ButtonIcon accessibilityLabel="test" iconName="Cross" isDisabled />
    </Box>
    <Box>
      <ButtonIcon
        withContainer
        accessibilityLabel="test"
        iconName="Cross"
        appearance="primary"
      />
      <ButtonIcon
        withContainer
        accessibilityLabel="test"
        iconName="Cross"
        appearance="secondary"
      />
      <ButtonIcon
        withContainer
        accessibilityLabel="test"
        iconName="Cross"
        appearance="neutral"
      />
      <ButtonIcon
        withContainer
        accessibilityLabel="test"
        iconName="Cross"
        appearance="danger"
      />
      <ButtonIcon
        withContainer
        accessibilityLabel="test"
        iconName="Cross"
        isLoading
      />
      <ButtonIcon
        withContainer
        accessibilityLabel="test"
        iconName="Cross"
        isDisabled
      />
    </Box>
    <Box>
      <ButtonIcon
        size="small"
        accessibilityLabel="test"
        iconName="Cross"
        appearance="primary"
      />
      <ButtonIcon
        size="small"
        accessibilityLabel="test"
        iconName="Cross"
        appearance="secondary"
      />
      <ButtonIcon
        size="small"
        accessibilityLabel="test"
        iconName="Cross"
        appearance="neutral"
      />
      <ButtonIcon
        size="small"
        accessibilityLabel="test"
        iconName="Cross"
        appearance="danger"
      />
      <ButtonIcon
        size="small"
        accessibilityLabel="test"
        iconName="Cross"
        isLoading
      />
      <ButtonIcon
        size="small"
        accessibilityLabel="test"
        iconName="Cross"
        isDisabled
      />
    </Box>
    <Box>
      <ButtonIcon
        size="small"
        withContainer
        accessibilityLabel="test"
        iconName="Cross"
        appearance="primary"
      />
      <ButtonIcon
        size="small"
        withContainer
        accessibilityLabel="test"
        iconName="Cross"
        appearance="secondary"
      />
      <ButtonIcon
        size="small"
        withContainer
        accessibilityLabel="test"
        iconName="Cross"
        appearance="neutral"
      />
      <ButtonIcon
        size="small"
        withContainer
        accessibilityLabel="test"
        iconName="Cross"
        appearance="danger"
      />
      <ButtonIcon
        size="small"
        withContainer
        accessibilityLabel="test"
        iconName="Cross"
        isLoading
      />
      <ButtonIcon
        size="small"
        withContainer
        accessibilityLabel="test"
        iconName="Cross"
        isDisabled
      />
    </Box>
  </Box>
);
