const RADIO_SIZE = 20;
export const RADIO_BORDER_WIDTH = 2;
export const RADIO_SHADOW_WIDTH = 2;
export const RADIO_SHADOW_CONTAINER_SIZE = RADIO_SIZE + RADIO_SHADOW_WIDTH * 2;
export const RADIO_CONTAINER_SIZE = RADIO_SIZE - RADIO_BORDER_WIDTH * 2;
export const RADIO_BORDER_CONTAINER_SIZE = RADIO_SIZE;
