const CHECKBOX_SIZE = 20;
export const CHECKBOX_BORDER_WIDTH = 2;
export const CHECKBOX_SHADOW_WIDTH = 2;
export const CHECKBOX_SHADOW_CONTAINER_SIZE =
  CHECKBOX_SIZE + CHECKBOX_SHADOW_WIDTH * 2;
export const CHECKBOX_CONTAINER_SIZE =
  CHECKBOX_SIZE - CHECKBOX_BORDER_WIDTH * 2;
export const CHECKBOX_BORDER_CONTAINER_SIZE = CHECKBOX_SIZE;
