name: Update expo dev branch
on:
  push:
    branches:
      - dev

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Publish update
        run: eas update --auto --branch development
