name: tests iOS
on: [pull_request]
jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 14 Pro'
      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install Expo
        run: |
          expo client:install:ios --latest
      - uses: dniHze/maestro-test-action@v1
        with:
          flow: packages/sandbox/e2e
          report: report.xml
